add deprecation warning for mapbox traces and mapbox subplot
plotly/plotly.js pull request #7087
Opened 2024-08-12 16:38 UTC by archmoj

With the introduction of `scattermap`, `choroplethmap` and `densitymap` as well as `map` subplots in #7060 this PR adds deprecation warnings to the description of `scattermapbox`, `choroplethmaboxp` and `densitymapbox` as well as `mapbox` subplots.

@plotly/plotly_js

2024-08-13 13:37 UTC, red-patience approved these changes
Okay for me if the style is consistent with other messages in this repo (not super familiar with  its conventions)

2024-08-13 15:24 UTC, ndrezn commented
Previous deprecation warning example for reference: https://github.com/plotly/plotly.js/pull/5447

2024-08-13 15:24 UTC, ndrezn commented on src/traces/densitymapbox/index.js
> +    'Please consider switching to the *scattermap* trace type and `map` subplots.'
```suggestion
    'Please consider switching to the *densitymap* trace type and `map` subplots.'
```
Right?

2024-08-13 15:25 UTC, ndrezn commented on test/plot-schema.json
> +    "description": "*choroplethmapbox* trace is deprecated! Please consider switching to the *scattermap* trace type and `map` subplots. GeoJSON features to be filled are set in `geojson` The data th
```suggestion
    "description": "*choroplethmapbox* trace is deprecated! Please consider switching to the * choroplethmap* trace type and `map` subplots. GeoJSON features to be filled are set in `geojson` The data that describes the choropleth value-to-color mapping is set in `locations` and `z`.",
```

Ditto here

2024-08-13 15:35 UTC, ndrezn reviewed
It doesn't look like these deprecations will appear in the console if these traces are used... is that correct?

2024-08-13 16:48 UTC, archmoj commented
> It doesn't look like these deprecations will appear in the console if these traces are used... is that correct? I would expect a console warning

A warning is now added in the console when using a `mapbox` subplot.

2024-08-13 19:43 UTC, emilykl commented on src/traces/choroplethmapbox/index.js
> +    'Please consider switching to the *choroplethmap* trace type and `map` subplots.'
@archmoj Maybe I'm out of the loop -- what does the "and `map` subplots" part of this message mean?

2024-08-13 21:15 UTC, emilykl commented on src/traces/choroplethmapbox/index.js
> +    'Please consider switching to the *choroplethmap* trace type and `map` subplots.'
never mind, I realize now this is referring to `map`, `map2`, etc. in the layout.

2024-08-21 15:52 UTC, ndrezn requested changes
Once we have the link for the migration docs available, we should include that link directly in this deprecation warning.

2024-08-26 13:44 UTC, archmoj commented
@ndrezn Would you please take over this PR?

2024-08-29 14:14 UTC, ndrezn commented
@archmoj , I've added the link where the JS migration guide will live (it is not live yet). I believe that `plot-schema.json` is autogenerated, I haven't run the build locally before -- could you regenerate this and add to the PR? I think then this PR is good to merge! 🥳

2024-08-29 14:41 UTC, merged